export enum TokenFornyetKeys {
  TILGANGSFEILSIDE_RENEWED = 'TILGANGSFEILSIDE_RENEWED',
  TILGANGSFEILSIDE_INFO = 'TILGANGSFEILSIDE_INFO',
  TILGANGSFEILSIDE_FORNYET = 'TILGANGSFEILSIDE_FORNYET',
  TILGANGSFEILSIDE_LOGIN = 'TILGANGSFEILSIDE_LOGIN'
}
