# This is a basic workflow to help you get started with Actions

name: Preprod

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:

  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - run: yarn install --frozen-lockfile
      - run: yarn install-peers
      - run: yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: helse-arbeidsgiver-felles-frontend-artifact
          path: ${{ github.workspace }}/dist/**/*

  Kodekvalitet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - run: yarn install --frozen-lockfile --no-build
      - run: yarn install-peers
      - run: yarn test

  Sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: "https://npm.pkg.github.com"
      - run: yarn install --frozen-lockfile
      - run: yarn run lint

  Snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
