# This is a basic workflow to help you get started with Actions

name: Produksjon

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  release:
    types: [published]

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  Bygg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: yarn install-peers
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: yarn run build
      - uses: actions/upload-artifact@v2
        with:
          name: helse-arbeidsgiver-felles-frontend-artifact
          path: ${{ github.workspace }}/dist/**/*

  Kodekvalitet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: yarn install --frozen-lockfile --no-build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: yarn install-peers
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - run: yarn test

  Publiser:
    needs: [Kodekvalitet,Bygg]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - uses: actions/download-artifact@v2
        with:
          name: helse-arbeidsgiver-felles-frontend-artifact
          path: dist
      - run: npm publish --access public --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
