on:
  push:
    branches: [ main ]
#on:
#  schedule:
#    - cron: '30 11 * * *'

name: Oppdatering av dependencies

jobs:

  Bygg:
    runs-on: ubuntu-latest
    steps:
      - name: Hent kode
        uses: actions/checkout@v2
      - name: Create Pull Request
          uses: peter-evans/create-pull-request@v3
          with:
            commit-message: Update report
            committer: Helse Arbeidsgiver <helsearbeidsgiver@nav.no>
            author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
            signoff: false
            labels: |
              report
              automated pr
